// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVQLZqX7AgauZBrFfnv5RpDcbr3QxFtOo',
    appId: '1:965703498965:web:1af77ce00109ea264bf65c',
    messagingSenderId: '965703498965',
    projectId: 'heroi-e2ae2',
    authDomain: 'heroi-e2ae2.firebaseapp.com',
    storageBucket: 'heroi-e2ae2.appspot.com',
    measurementId: 'G-W6XKY8PQ7Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRnDQb-srm0CJFz6APo8icRAzSTw3EOsE',
    appId: '1:965703498965:android:22ba8f53a8e98df14bf65c',
    messagingSenderId: '965703498965',
    projectId: 'heroi-e2ae2',
    storageBucket: 'heroi-e2ae2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY-JJarQlPQViReM6k2gk7xB5qN6fsoww',
    appId: '1:965703498965:ios:db25eae182c0febe4bf65c',
    messagingSenderId: '965703498965',
    projectId: 'heroi-e2ae2',
    storageBucket: 'heroi-e2ae2.appspot.com',
    iosBundleId: 'com.example.sushiresProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAY-JJarQlPQViReM6k2gk7xB5qN6fsoww',
    appId: '1:965703498965:ios:db25eae182c0febe4bf65c',
    messagingSenderId: '965703498965',
    projectId: 'heroi-e2ae2',
    storageBucket: 'heroi-e2ae2.appspot.com',
    iosBundleId: 'com.example.sushiresProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVQLZqX7AgauZBrFfnv5RpDcbr3QxFtOo',
    appId: '1:965703498965:web:b1687b6aa8721bbb4bf65c',
    messagingSenderId: '965703498965',
    projectId: 'heroi-e2ae2',
    authDomain: 'heroi-e2ae2.firebaseapp.com',
    storageBucket: 'heroi-e2ae2.appspot.com',
    measurementId: 'G-ZC4Y573X9S',
  );
}
